name: 🚀 Deploy Health Checker

'on':
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west1
  SERVICE_NAME: checker
  REPOSITORY: checker

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: 🏗️ Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔐 Check for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📥 Install dependencies
        run: npm install

      - name: 🧪 Run Tests
        run: npm test

      - name: 🔐 Google Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/992838171690/locations/global/workloadIdentityPools/github-actions-pool/providers/checker'
          service_account: 'github-actions-sa@repo-490410.iam.gserviceaccount.com'
          export_environment_variables: true
          create_credentials_file: true

      - name: ⚙️ Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: 🐳 Docker Auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: 📤 Build and Push Container
        run: |
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:latest"
          docker build -t $DOCKER_TAG .
          docker push $DOCKER_TAG

      - name: 🚀 Deploy Cloud Run Job
        run: |
          if gcloud run jobs describe ${{ env.SERVICE_NAME }} --region=${{ env.REGION }} 2>/dev/null; then
            gcloud run jobs update ${{ env.SERVICE_NAME }} \
              --image="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:latest" \
              --region=${{ env.REGION }}
          else
            gcloud run jobs create ${{ env.SERVICE_NAME }} \
              --image="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:latest" \
              --region=${{ env.REGION }} \
              --set-env-vars=HEALTH_CHECK_URLS=${{ secrets.HEALTH_CHECK_URLS }}
          fi

      - name: 🔥 Run and verify job
        run: |
          gcloud run jobs execute ${{ env.SERVICE_NAME }} \
            --region=${{ env.REGION }} \
            --wait